/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as KrakowIndexRouteImport } from './routes/krakow/index'
import { Route as KrakowStoryIdRouteImport } from './routes/krakow/$storyId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const KrakowIndexRoute = KrakowIndexRouteImport.update({
  id: '/krakow/',
  path: '/krakow/',
  getParentRoute: () => rootRouteImport,
} as any)
const KrakowStoryIdRoute = KrakowStoryIdRouteImport.update({
  id: '/krakow/$storyId',
  path: '/krakow/$storyId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/krakow/$storyId': typeof KrakowStoryIdRoute
  '/krakow/': typeof KrakowIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/krakow/$storyId': typeof KrakowStoryIdRoute
  '/krakow': typeof KrakowIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/krakow/$storyId': typeof KrakowStoryIdRoute
  '/krakow/': typeof KrakowIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/krakow/$storyId' | '/krakow/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/krakow/$storyId' | '/krakow'
  id: '__root__' | '/' | '/krakow/$storyId' | '/krakow/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  KrakowStoryIdRoute: typeof KrakowStoryIdRoute
  KrakowIndexRoute: typeof KrakowIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/krakow/': {
      id: '/krakow/'
      path: '/krakow'
      fullPath: '/krakow/'
      preLoaderRoute: typeof KrakowIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/krakow/$storyId': {
      id: '/krakow/$storyId'
      path: '/krakow/$storyId'
      fullPath: '/krakow/$storyId'
      preLoaderRoute: typeof KrakowStoryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  KrakowStoryIdRoute: KrakowStoryIdRoute,
  KrakowIndexRoute: KrakowIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
